import type { Metadata } from 'next';
import './globals.css';
import { LangProvider } from '@/context/LangContext';
import Navbar from '@/sections/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={` antialiased font-normal text-base-content bg-base-200 lg:text-[18px]`}
		>
			<LangProvider>
				<body>
					<Navbar />
					{children}
				</body>
			</LangProvider>
		</html>
	);
}
